[package]
name = "mcp9600"
version = "0.1.0"
authors = ["Andrew Hepp <drewhepp@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.3"
shared-bus = "0.1.4"
